### PR TITLE
Add cmake project files

### PR DESCRIPTION
**Pull request by qwerity**
- cleanup the lib
- separated library code and test binary code

### CODE REVIEW

**Comment by peihongch** [comment]
Oh, I almost forgot about this repo. Has it been helpful to you?

**Comment by peihongch** [comment]
Perhaps you have completed thorough testing; if so, please let me know, and I'd be happy to merge your patch.

**Comment by qwerity** [comment]
Yeah I was tested on Linux/Ubuntu and Windows 11 with cuda 12.6!
Yes Thanks! May be later I will add some other hashing functionality as well!

**Comment by peihongch** [comment]
LGTM

**Pull request merged**
